backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
collections:
  - name: "aktuality"
    label: "Aktuality"
    folder: "aktuality"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{articletitle | slugify}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/aktualita.njk"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "aktuality"}
      - {label: "Název aktuality", name: "articletitle", widget: "string"}
      - {label: "Datum publikování", name: "date", widget: "datetime"}
      - {label: "Autor aktuality", name: "autor", widget: "select", options: ["Ladislav Kratochvil", "Jana Levá"]}
      - {label: "Obrázek u aktuality", name: "foto", widget: "image", required: false }
      - {label: "Obsah aktuality", name: "body", widget: "markdown"}